spring:
  config:
    activate:
      on-profile: conta
  application:
    name: conta-service
#  server:
#    port: 9000  # Porta específica para o conta.service
    # Ao entrar no localhost:9000/h2-console
  datasource:
    url: jdbc:h2:file:./data/conta_service
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: bacen
  application:
    name: bacen-service
#server:
#    port: 9001  # Porta específica para o bacen.service
  datasource:
    url: jdbc:h2:file:./data/bacen_service
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
---
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE

